var l=void 0,o=!0,p=null,G=!1;function Q(){return function(d){return d}}function X(){return function(){}}
(function(d){function e(c){var b=m["$"+c]||window[c];if(!b)throw Error("Ender Error: Requested module '"+c+"' has not been defined.");return b}function h(c,b){return m["$"+c]=b}function i(b,d){var m,e;this.O=b;"undefined"==typeof b?(m=[],this.O=""):m="string"==typeof b||b.nodeName||b.length&&"item"in b||b==window?c.Oa(b,d):isFinite(b.length)?b:[b];for(e=this.length=m.length;e--;)this[e]=m[e]}function c(b,c){return new i(b,c)}d.global=d;var m={},q=d.$,b=d.ender,v=d.require,r=d.provide;d.provide=h;
d.require=e;i.prototype.forEach=function(b,c){var d,m;d=0;for(m=this.length;d<m;++d)d in this&&b.call(c||this[d],this[d],d,this);return this};i.prototype.Q=c;c._VERSION="0.4.3-dev";c.ie=i.prototype;c.l=function(b,d){var m=d?i.prototype:c,e;for(e in b)"noConflict"!=e&&"_VERSION"!=e&&(m[e]=b[e])};c.Oa=function(b,c){return"string"==typeof b?(c||document).querySelectorAll(b):b.nodeName?[b]:b};c.kb=function(c){d.$=q;c&&(d.provide=r,d.require=v,d.ender=b,"function"==typeof c&&c(e,h,this));return this};
"undefined"!==typeof module&&module.b&&(module.b=c);d.ender=d.$=c})(this);
(function(){!function(d){function e(c,d){"string"===typeof c&&(c=document.getElementById(c));if(c){var e=c.getElementsByTagName("div")[0];e&&-1!==e.className.search(/(^|\s)handle(\s|$)/)&&(this.ab(c,e,d||{}),this.nd())}}var h={x:0,y:0,ab:function(){this.Vb("mouse");this.Vb("touch")},Vb:function(c){var d=document["on"+c+"move"]||X();document["on"+c+"move"]=function(c){d(c);h.refresh(c)}},refresh:function(c){c||(c=window.event);"mousemove"===c.type?this.set(c):c.touches&&this.set(c.touches[0])},set:function(c){if(c.pageX||
c.pageY)this.x=c.pageX,this.y=c.pageY;else if(c.clientX||c.clientY)this.x=c.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,this.y=c.clientY+document.body.scrollTop+document.documentElement.scrollTop}};h.ab();var i={get:function(c){var d=curtop=0;if(c.offsetParent){do d+=c.offsetLeft,curtop+=c.offsetTop;while(c=c.offsetParent)}return[d,curtop]}};e.prototype={ab:function(c,d,e){this.g=c;this.handle=d;this.options=e;this.disabled=this.n("disabled",G);this.Sc=this.n("horizontal",
o);this.xd=this.n("vertical",G);this.$b=this.n("slide",o);this.P=this.n("steps",0);this.Da=this.n("snap",G);this.$c=this.n("loose",G);this.speed=this.n("speed",10)/100;this.Ad=this.n("xPrecision",0);this.Cd=this.n("yPrecision",0);this.o=e.o||p;this.pa=e.pa||p;this.a={left:e.left||0,right:-(e.right||0),top:e.top||0,bottom:-(e.bottom||0),Ka:0,fc:0,mb:0,La:0,gc:0,nb:0};this.value={ga:[-1,-1],e:[e.x||0,e.y||0],target:[e.x||0,e.y||0]};this.d={g:[0,0],jb:[0,0],ga:[-999999,-999999],e:[0,0],target:[0,0]};
this.sa=[0,0];this.Ga=this.B=this.Qa=G},n:function(c,d){return this.options[c]!==l?this.options[c]:d},nd:function(){this.Zb();this.kd();this.Tb();this.md();this.oc()},Zb:function(){this.d.g=i.get(this.g)},kd:function(){!this.a.left&&!this.a.right&&(this.a.left=i.get(this.handle)[0]-this.d.g[0],this.a.right=-this.a.left);!this.a.top&&!this.a.bottom&&(this.a.top=i.get(this.handle)[1]-this.d.g[1],this.a.bottom=-this.a.top)},Tb:function(){this.a.Ka=this.a.left;this.a.fc=this.g.offsetWidth+this.a.right;
this.a.mb=this.a.fc-this.a.Ka-this.handle.offsetWidth;this.a.La=this.a.top;this.a.gc=this.g.offsetHeight+this.a.bottom;this.a.nb=this.a.gc-this.a.La-this.handle.offsetHeight;this.a.Bd=1/(this.Ad||Math.max(this.g.offsetWidth,this.handle.offsetWidth));this.a.Dd=1/(this.Cd||Math.max(this.g.offsetHeight,this.handle.offsetHeight))},md:function(){if(1<this.P){this.Fa=[];for(var c=0;c<=this.P-1;c++)this.Fa[c]=c/(this.P-1)}},oc:function(){var c=this;this.g.Pe=function(){return G};this.handle.onmousedown=
this.handle.ontouchstart=function(b){c.Oc(b)};this.g.onmousedown=this.g.ontouchstart=function(b){c.zd(b)};var d=document.onmouseup||X();document.onmouseup=function(b){d(b);c.Ab(b)};var e=document.ontouchend||X();document.ontouchend=function(b){e(b);c.Ab(b)};var b=window.onresize||X();window.onresize=function(d){b(d);c.Fc(d)};this.g.onmousemove=function(){c.Qa=o};this.g.onclick=function(){return!c.Qa};this.Mb=setInterval(function(){c.vb()},25);c.vb(G,o)},Oc:function(c){this.Qa=G;h.refresh(c);this.Sb(c,
o);this.qd();this.uc(c)},zd:function(c){h.refresh(c);this.Sb(c,o);this.rd()},Ab:function(){this.sd();this.td()},Fc:function(){this.Zb();this.Tb();this.update()},rd:function(c){this.disabled||(this.Ga=o,c===l&&(c=[h.x-this.d.g[0]-this.handle.offsetWidth/2,h.y-this.d.g[1]-this.handle.offsetHeight/2]),this.Xb(c))},td:function(){!this.disabled&&this.Ga&&(this.Ga=G,this.Yb(this.value.e),this.result())},qd:function(){this.disabled||(this.d.jb=[h.x-i.get(this.handle)[0],h.y-i.get(this.handle)[1]],this.B=
o)},sd:function(){if(!this.disabled&&this.B){this.B=G;var c=this.Za(this.value.e);if(this.$b){var d=this.sa;c[0]+=4*d[0];c[1]+=4*d[1]}this.Yb(c);this.result()}},Jc:function(){var c=this.value.e;this.Da&&1<this.P&&(c=this.Xa(c));this.Ib(c,this.value.ga)||("function"===typeof this.pa&&this.pa(c[0],c[1]),this.Y(this.value.ga,c))},result:function(){"function"==typeof this.o&&this.o(this.value.target[0],this.value.target[1])},vb:function(c,d){if(!c||this.B){if(this.B){var e=this.Za(this.value.target);
this.Xb([h.x-this.d.g[0]-this.d.jb[0],h.y-this.d.g[1]-this.d.jb[1]],this.$c);this.sa=[this.value.target[0]-e[0],this.value.target[1]-e[1]]}(this.B||d)&&this.Y(this.value.e,this.value.target);if(this.B||this.Nc()||d)this.update(),this.Jc()}},Nc:function(){var c=[this.value.target[0]-this.value.e[0],this.value.target[1]-this.value.e[1]];if(!c[0]&&!c[1])return G;Math.abs(c[0])>this.a.Bd||Math.abs(c[1])>this.a.Dd?(this.value.e[0]+=c[0]*this.speed,this.value.e[1]+=c[1]*this.speed):this.Y(this.value.e,
this.value.target);return o},update:function(){this.d.e=this.Da?this.ua(this.Xa(this.value.e)):this.ua(this.value.e);this.show()},show:function(){this.Ib(this.d.e,this.d.ga)||(this.Sc&&(this.handle.style.left=""+this.d.e[0]+"px"),this.xd&&(this.handle.style.top=""+this.d.e[1]+"px"),this.Y(this.d.ga,this.d.e))},Yb:function(c,d){var e=d?this.Fb(c):this.Ya(c);this.Y(this.value.target,e);this.d.target=this.ua(e)},Xb:function(c,d){var e=this.Mc(c),e=d?this.Fb(e):this.Ya(e);this.Y(this.value.target,e);
this.d.target=this.ua(e)},Fb:function(c){var d=this.Ya(c);return[d[0]+(c[0]-d[0])/4,d[1]+(c[1]-d[1])/4]},Ya:function(c){c=this.Za(c);c[0]=Math.max(c[0],0);c[1]=Math.max(c[1],0);c[0]=Math.min(c[0],1);c[1]=Math.min(c[1],1);if(!this.B&&!this.Ga||this.Da)1<this.P&&(c=this.Xa(c));return c},Mc:function(c){return[this.Hb(c[0],this.a.mb,this.a.Ka),this.Hb(c[1],this.a.nb,this.a.La)]},Hb:function(c,d,e){return d?(c-e)/d:0},ua:function(c){return[this.Gb(c[0],this.a.mb,this.a.Ka),this.Gb(c[1],this.a.nb,this.a.La)]},
Gb:function(c,d,e){return Math.round(c*d)+e},Xa:function(c){return[this.Eb(c[0]),this.Eb(c[1])]},Eb:function(c){for(var d=0,e=1,b=0;b<=this.P-1;b++)Math.abs(this.Fa[b]-c)<e&&(e=Math.abs(this.Fa[b]-c),d=b);return this.Fa[d]},Ib:function(c,d){return c[0]===d[0]&&c[1]===d[1]},Y:function(c,d){c[0]=d[0];c[1]=d[1]},Za:function(c){return[c[0],c[1]]},Sb:function(c,d){c||(c=window.event);c.preventDefault&&c.preventDefault();c.returnValue=G;d&&document.selection&&document.selection.empty()},uc:function(c){c||
(c=window.event);c.stopPropagation&&c.stopPropagation();c.cancelBubble=o}};d.dragdealer=function(c,d){return new e(c,d)}}(this);provide("ender-dragdealer",{});!function(d){d.l({Gc:function(d){return dragdealer(this[0],d)}},o)}(ender)})();
(function(){var d={b:{}};!function(e,h,i){"undefined"!=typeof d&&d.b?d.b=i(e,h):"function"==typeof define&&"object"==typeof define.qc?define(i):h[e]=i(e,h)}("bean",this,function(d,h){function i(g,d,j,e){var h,x,f,n,t,z;if(j===l&&"object"==typeof d)for(h in d)d.hasOwnProperty(h)&&i.call(this,g,h,d[h]);else{"function"==typeof j?(n=u.call(arguments,3),e=h=j):(h=e,n=u.call(arguments,4),e=m(j,h));x=k(d);this===D&&(e=b(c,g,d,e,h));for(f=x.length;f--;)z=A.put(t=new K(g,x[f].replace(w,""),e,h,k(x[f].replace(E,
""),"."),n,G)),t[B]&&z&&a(g,t.W,o,t.xc);return g}}function c(a,b,g){var d="string"==typeof b,j,e;if(d&&0<b.indexOf(" ")){b=k(b);for(e=b.length;e--;)c(a,b[e],g);return a}if((e=d&&b.replace(w,""))&&J[e])e=J[e].type;if(!b||d){if(b=d&&b.replace(E,""))b=k(b,".");q(a,e,g,b)}else if("function"==typeof b)q(a,p,b);else for(j in b)b.hasOwnProperty(j)&&c(a,j,b[j]);return a}function m(a,b){function c(a){var d=g(a.target,this);d&&b.apply(d,arguments)}function g(b,c){for(var f,n="string"==typeof a?N(a,c):a;b&&
b!==c;b=b.parentNode)for(f=n.length;f--;)if(n[f]===b)return b}c.v={Cb:g,O:a};return c}function q(b,c,g,d){var c=c&&c.replace(w,""),c=A.get(b,c,p,G),j={},e,f;e=0;for(f=c.length;e<f;e++)if((!g||c[e].za===g)&&c[e].Kb(d))A.xb(c[e]),!j[c[e].W]&&c[e][B]&&(j[c[e].W]={ac:c[e].W,ra:c[e].type});for(e in j)A.c(b,j[e].ac,p,G)||a(b,j[e].ac,G,j[e].ra)}function b(a,b,c,g,d){return function(){g.apply(this,arguments);a(b,c,d)}}function v(a,b){if(y||!b||!(a&&a.propertyName!="_on"+b)){var c=A.get(this,b||a.type,p,G),
g=c.length,d=0,a=new O(a,this,o);b&&(a.type=b);for(;d<g&&!a.fb();d++)c[d].gd||c[d].L.call(this,a)}}function r(a){N=arguments.length?a:F.querySelectorAll?function(a,b){return b.querySelectorAll(a)}:function(){throw Error("Bean: No selector engine installed");}}function k(a,b){return a.split(b||" ")}var s=window,I=h[d],E=/[^\.]*(?=\..*)\.|.*/,w=/\..*/,F=document||{},C=F.documentElement||{},y=C.addEventListener,B=y?"addEventListener":"attachEvent",D={},u=Array.prototype.slice,L=function(a,b,c){for(c=
0;c<b.length;c++)b[c]&&(a[b[c]]=1);return a}({},k("click dblclick mouseup mousedown contextmenu mousewheel mousemultiwheel DOMMouseScroll mouseover mouseout mousemove selectstart selectend keydown keypress keyup orientationchange focus blur change reset select submit load unload beforeunload resize move DOMContentLoaded readystatechange message error abort scroll "+(y?"show input invalid touchstart touchmove touchend touchcancel gesturestart gesturechange gestureend textinputreadystatechange pageshow pagehide popstate hashchange offline online afterprint beforeprint dragstart dragenter dragover dragleave drag drop dragend loadstart progress suspend emptied stalled loadmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate play pause ratechange volumechange cuechange checking noupdate downloading cached updateready obsolete ":
""))),J=function(){function a(c){c=c.relatedTarget;return!c?c==p:c!==this&&"xul"!==c.prefix&&!/document/.test(this.toString())&&!b(c,this)}var b="compareDocumentPosition"in C?function(a,b){return b.compareDocumentPosition&&16===(b.compareDocumentPosition(a)&16)}:"contains"in C?function(a,b){b=9===b.nodeType||b===window?C:b;return b!==a&&b.contains(a)}:function(a,b){for(;a=a.parentNode;)if(a===b)return 1;return 0};return{Ke:{qa:"mouseover",Ua:a},Le:{qa:"mouseout",Ua:a},Me:{qa:/Firefox/.test(navigator.userAgent)?
"DOMMouseScroll":"mousewheel"}}}(),O=function(){function a(f,b,c){if(arguments.length&&(this.D=f=f||((b.ownerDocument||b.document||b).parentWindow||s).event,this.Ob=c,f)){var n=f.type,g=f.target||f.srcElement,d,t,j;this.target=g&&3===g.nodeType?g.parentNode:g;if(c){j=Z[n];if(!j){g=0;for(d=M.length;g<d;g++)if(M[g].F.test(n)){Z[n]=j=M[g].C;break}}n=j(f,this,n);for(g=n.length;g--;)if(!((t=n[g])in this)&&t in f)this[t]=f[t]}}}var b=k("altKey attrChange attrName bubbles cancelable ctrlKey currentTarget detail eventPhase getModifierState isTrusted metaKey relatedNode relatedTarget shiftKey srcElement target timeStamp type view which propertyName"),
c=b.concat(k("button buttons clientX clientY dataTransfer fromElement offsetX offsetY pageX pageY screenX screenY toElement")),g=c.concat(k("wheelDelta wheelDeltaX wheelDeltaY wheelDeltaZ axis")),d=b.concat(k("char charCode key keyCode keyIdentifier keyLocation location")),j=b.concat(k("data")),f=b.concat(k("touches targetTouches changedTouches scale rotation")),n=b.concat(k("data origin source")),t=b.concat(k("state")),e=/over|out/,M=[{F:/key/i,C:function(f,a){a.keyCode=f.keyCode||f.which;return d}},
{F:/click|mouse(?!(.*wheel|scroll))|menu|drag|drop/i,C:function(f,a,b){a.cf=3===f.which||2===f.button;a.Ve={x:0,y:0};if(f.pageX||f.pageY)a.clientX=f.pageX,a.clientY=f.pageY;else if(f.clientX||f.clientY)a.clientX=f.clientX+F.body.scrollLeft+C.scrollLeft,a.clientY=f.clientY+F.body.scrollTop+C.scrollTop;e.test(b)&&(a.relatedTarget=f.relatedTarget||f[("mouseover"==b?"from":"to")+"Element"]);return c}},{F:/mouse.*(wheel|scroll)/i,C:function(){return g}},{F:/^text/i,C:function(){return j}},{F:/^touch|^gesture/i,
C:function(){return f}},{F:/^message$/i,C:function(){return n}},{F:/^popstate$/i,C:function(){return t}},{F:/.*/,C:function(){return b}}],Z={};a.prototype.preventDefault=function(){this.D.preventDefault?this.D.preventDefault():this.D.returnValue=G};a.prototype.stopPropagation=function(){this.D.stopPropagation?this.D.stopPropagation():this.D.cancelBubble=o};a.prototype.stop=function(){this.preventDefault();this.stopPropagation()};a.prototype.fb=function(){return this.D.fb&&this.D.fb()};a.prototype.h=
function(f){var b=new a(this,this.element,this.Ob);b.currentTarget=f;return b};return a}(),K=function(){function a(g,d,j,e,f,n,t){var z=J[d];"unload"==d&&(j=b(q,g,d,j,e));z&&(z.Ua&&(j=c(g,j,z.Ua,n)),d=z.qa||d);this.Ob=z=L[d]&&!!g[B];this.xc=!y&&!z&&d;this.element=g;this.type=d;this.za=e;this.namespaces=f;this.W=y||z?d:"propertychange";this.target=!y&&!z&&(g===F||g===s)?C:g;this[B]=!!this.target[B];this.root=t;this.L=c(g,j,p,n)}function c(a,b,g,d){var f=g?function(f){var c=b.v?b.v.Cb(f.target,a):this;
if(g.apply(c,arguments))return f&&(f.currentTarget=c),b.apply(a,d?u.call(arguments,f?0:1).concat(d):arguments)}:function(f){b.v&&(f=f.h(b.v?b.v.Cb(f.target,a):l));return b.apply(a,d?u.call(arguments,f?0:1).concat(d):arguments)};f.v=b.v;return f}a.prototype.Kb=function(a){var b,c,g=0;if(!a)return o;if(!this.namespaces)return G;for(b=a.length;b--;)for(c=this.namespaces.length;c--;)a[b]==this.namespaces[c]&&g++;return a.length===g};a.prototype.Qb=function(a,b,c){return this.element===a&&(!b||this.za===
b)&&(!c||this.L===c)};return a}(),A=function(){function a(c,g,d,j,f,n){var t=f?"r":"$";if(!g||"*"==g)for(var e in b)e.charAt(0)==t&&a(c,e.substr(1),d,j,f,n);else{f=0;e=b[t+g];var M="*"==c;if(e)for(t=e.length;f<t&&(!M&&!e[f].Qb(c,d,j)||n(e[f],e,f,g));f++);}}var b={};return{c:function(a,c,g,d){if(d=b[(d?"r":"$")+c])for(c=d.length;c--;)if(!d[c].root&&d[c].Qb(a,g,p))return o;return G},get:function(b,c,g,d){var f=[];a(b,c,g,p,d,function(a){return f.push(a)});return f},put:function(a){var c=!a.root&&!this.c(a.element,
a.type,p,G),g=(a.root?"r":"$")+a.type;(b[g]||(b[g]=[])).push(a);return c},xb:function(c){a(c.element,c.type,p,c.L,c.root,function(a,c,g){c.splice(g,1);a.gd=o;0===c.length&&delete b[(a.root?"r":"$")+a.type];return G})},Ic:function(){var a,c=[];for(a in b)"$"==a.charAt(0)&&(c=c.concat(b[a]));return c}}}(),N,a=y?function(a,b,c){a[c?"addEventListener":"removeEventListener"](b,v,G)}:function(a,b,c,g){if(c)A.put(b=new K(a,g||b,function(b){v.call(a,b,g)},v,p,p,o)),g&&a["_on"+g]==p&&(a["_on"+g]=0),b.target.attachEvent("on"+
b.W,b.L);else if(b=A.get(a,g||b,v,o)[0])b.target.detachEvent("on"+b.W,b.L),A.xb(b)},g=y?function(a,b,c){var g=F.createEvent(a?"HTMLEvents":"UIEvents");g[a?"initEvent":"initUIEvent"](b,o,o,s,1);c.dispatchEvent(g)}:function(a,b,c){c=!y&&!a&&(c===F||c===s)?C:c;a?c.fireEvent("on"+b,F.createEventObject()):c["_on"+b]++},j={N:i,add:function(a,b,c,g){return i.apply(p,"string"!=typeof c?u.call(arguments):[a,c,b,g].concat(3<arguments.length?u.call(arguments,5):[]))},cd:function(){return i.apply(D,arguments)},
ya:c,remove:c,h:function(a,b,c){for(var b=A.get(b,c,p,G),c=b.length,g=0,d,j;g<c;g++)b[g].za&&(d=[a,b[g].type],(j=b[g].L.v)&&d.push(j.O),d.push(b[g].za),i.apply(p,d));return a},ge:function(a,b,c){var d=k(b),j,e,f,n;for(j=d.length;j--;){b=d[j].replace(w,"");if(f=d[j].replace(E,""))f=k(f,".");if(!f&&!c&&a[B])g(L[b],b,a);else{n=A.get(a,b,p,G);c=[G].concat(c);b=0;for(e=n.length;b<e;b++)n[b].Kb(f)&&n[b].L.apply(a,c)}}return a},ld:r,kb:function(){h[d]=I;return this}};if(s.attachEvent){var x=function(){var a,
b=A.Ic();for(a in b)b[a].type&&"unload"!==b[a].type&&c(b[a].element,b[a].type);s.detachEvent("onunload",x);s.hc&&s.hc()};s.attachEvent("onunload",x)}r();return j});provide("bean",d.b);!function(d){function h(b,c){var d=c?[c]:[];return function(){for(var e=0,h=this.length;e<h;e++)!arguments.length&&("on"==b&&c)&&(b="fire"),i[b].apply(this,[this[e]].concat(d,Array.prototype.slice.call(arguments,0)));return this}}for(var i=require("bean"),c=h("on"),m=h("off"),q=h("fire"),c={N:c,Nd:c,bind:c,He:c,Cc:h("add"),
cd:h("one"),ya:m,Ha:m,wf:m,$e:m,uf:m,ee:q,f:q,Ta:h("clone"),oe:function(b,c,d){for(d=this.length;d--;)i.N.call(this,this[d],"mouseenter",b),i.N.call(this,this[d],"mouseleave",c);return this}},m="blur change click dblclick error focus focusin focusout keydown keypress keyup load mousedown mouseenter mouseleave mouseout mouseover mouseup mousemove resize scroll select submit unload".split(" "),q=m.length;q--;)c[m[q]]=h("on",m[q]);i.ld(d);d.l(c,o)}(ender)})();
(function(){var d={b:{}};(function(e,h,i){"undefined"!=typeof d&&d.b?d.b=h():"function"==typeof i.define&&i.define.amd?define(e,h):i[e]=h()})("bonzo",function(){function d(a,b,f,c){for(var g,n=0,j=a.length;n<j;n++)g=c?a.length-n-1:n,b.call(f||a[g],a[g],g,a);return a}function h(a,f,c){for(var g=0,d=a.length;g<d;g++)b(a[g])&&(h(a[g].childNodes,f,c),f.call(c||a[g],a[g],g,a));return a}function i(a){return a.replace(/-(.)/g,function(a,b){return b.toUpperCase()})}function c(a){a[f]("data-node-uid")||a[T]("data-node-uid",
++V);a=a[f]("data-node-uid");return H[a]||(H[a]={})}function m(a){(a=a[f]("data-node-uid"))&&delete H[a]}function q(a){var b;try{return a===p||a===l?l:"true"===a?o:"false"===a?G:"null"===a?p:(b=parseFloat(a))==a?b:a}catch(f){}}function b(a){return a&&a.nodeName&&(1==a.nodeType||11==a.nodeType)}function v(a){"transform"==a&&(a=n.transform)||/^transform-?[Oo]rigin$/.test(a)&&(a=n.transform+"Origin")||"float"==a&&(a=n.cssFloat);return a?i(a):p}function r(a,b,f,c){var g=0,n=b||this,j=[],a=L&&"string"==
typeof a&&"<"!=a.charAt(0)?L(a):a;d(E(a),function(a,b){d(n,function(c){f(a,j[g++]=0<b?w(n,c):c)},p,c)},this,c);n.length=g;d(j,function(a){n[--g]=a},p,!c);return n}function k(a,b,f){var c=y(a),g=c.A("position"),d=c.d(),n="relative"==g,j=[parseInt(c.A("left"),10),parseInt(c.A("top"),10)];"static"==g&&c.A("position","relative");isNaN(j[0])&&(j[0]=n?0:a.offsetLeft);isNaN(j[1])&&(j[1]=n?0:a.offsetTop);b!=p&&(a.style.left=b-d.left+j[0]+R);f!=p&&(a.style.top=f-d.top+j[1]+R)}function s(a,b){return"function"==
typeof b?b(a):b}function I(a){this.length=0;if(a){a="string"!==typeof a&&!a.nodeType&&"undefined"!==typeof a.length?a:[a];this.length=a.length;for(var b=0;b<a.length;b++)this[b]=a[b]}}function E(a,f,c){var g,d;if("string"==typeof a)return y.create(a);b(a)&&(a=[a]);if(c){d=[];c=0;for(g=a.length;c<g;c++)d[c]=w(f,a[c]);return d}return a}function w(a,b){var f=b.cloneNode(o),c,g;if(a.Q&&"function"==typeof a.Ta){a.Q(f).Ta(b);c=a.Q(f).find("*");g=a.Q(b).find("*");for(var d=0;d<g.length;d++)a.Q(c[d]).Ta(g[d])}return f}
function F(a,b,f){var c=this[0];if(!c)return this;if(a==p&&b==p)return(C(c)?{x:B.pageXOffset||u.scrollLeft,y:B.pageYOffset||u.scrollTop}:{x:c.scrollLeft,y:c.scrollTop})[f];C(c)?B.scrollTo(a,b):(a!=p&&(c.scrollLeft=a),b!=p&&(c.scrollTop=b));return this}function C(a){return a===B||/^(?:body|html)$/i.test(a.tagName)}function y(a){return new I(a)}var B=window,D=B.document,u=D.documentElement,L=p,J=/^(checked|value|selected|disabled)$/i,O=/^(select|fieldset|table|tbody|tfoot|td|tr|colgroup)$/i,K=["<table>",
"</table>",1],A=["<table><tbody><tr>","</tr></tbody></table>",3],N=["<select>","</select>",1],a=["_","",0,1],g={qf:K,lf:K,of:K,Wd:K,caption:K,tf:["<table><tbody>","</tbody></table>",2],pf:A,mf:A,Vd:["<table><colgroup>","</colgroup></table>",2],fe:["<form>","</form>",1],Ge:["<form><fieldset>","</fieldset></form>",2],Re:N,Qe:N,df:a,style:a,link:a,Te:a,qa:a},j=/^(checked|selected|disabled)$/,x=/msie/i.test(navigator.userAgent),H={},V=0,U=/^-?[\d\.]+$/,S=/^data-(.+)$/,R="px",T="setAttribute",f="getAttribute",
n=function(){var a=D.createElement("p");a.innerHTML='<a href="#x">x</a><table style="float:left;"></table>';var b="#x"!=a.getElementsByTagName("a")[0][f]("href"),c=0!==a.getElementsByTagName("tbody").length,g=D.defaultView&&D.defaultView.getComputedStyle,d=a.getElementsByTagName("table")[0].style.styleFloat?"styleFloat":"cssFloat",n;a:{var j=["transform","webkitTransform","MozTransform","OTransform","msTransform"],t;for(t=0;t<j.length;t++)if(j[t]in a.style){n=j[t];break a}}return{Tc:b,sc:c,wc:g,cssFloat:d,
transform:n,classList:"classList"in a,dd:"undefined"!==typeof D.createElement("a").style.opacity}}(),t={lineHeight:1,zoom:1,zIndex:1,opacity:1,Sd:1,WebkitBoxFlex:1,MozBoxFlex:1},z=n.wc?function(a,b){var f=p,c=D.defaultView.getComputedStyle(a,"");c&&(f=c[b]);return a.style[b]||f}:x&&u.currentStyle?function(a,b){if("opacity"==b&&!n.dd){var f=100;try{f=a.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(c){try{f=a.filters("alpha").opacity}catch(g){}}return f/100}f=a.currentStyle?a.currentStyle[b]:
p;return a.style[b]||f}:function(a,b){return a.style[b]};I.prototype={get:function(a){return this[a]||p},i:function(a,b){return d(this,a,b)},zc:function(a,b){return h(this,a,b)},map:function(a,b){var f=[],c,g;for(g=0;g<this.length;g++)c=a.call(this,this[g],g),b?b(c)&&f.push(c):f.push(c);return f},Vc:function(a,b){function f(d,n){try{if(b||"string"==typeof a&&!O.test(d.tagName))return d[g]=a}catch(j){}c(d,n)}function c(b,f){d(E(a,n,f),function(a){b.appendChild(a)})}var g=b?u.textContent===l?"innerText":
"textContent":"innerHTML",n=this;return"undefined"!=typeof a?this.empty().i(f):this[0]?this[0][g]:""},Ra:function(a,b){return r.call(this,a,b,function(a,b){a.appendChild(b)})},Rb:function(a,b){return r.call(this,a,b,function(a,b){a.insertBefore(b,a.firstChild)},1)},pc:function(a){var b=this;return this.i(function(f,c){d(E(a,b,c),function(a){f.parentNode.insertBefore(a,f.nextSibling)},p,1)})},insertBefore:function(a,b){return r.call(this,a,b,function(a,b){a.parentNode.insertBefore(b,a)})},Lb:function(a,
b){return r.call(this,a,b,function(a,b){var f=a.nextSibling;f?a.parentNode.insertBefore(b,f):a.parentNode.appendChild(b)},1)},show:function(a){a="string"==typeof a?a:"";return this.i(function(b){b.style.display=a})},Rc:function(){return this.i(function(a){a.style.display="none"})},ta:function(){return y(this.length?this[0]:[])},Pb:function(){return y(this.length?this[this.length-1]:[])},next:function(){return this.lb("nextSibling")},Ba:function(){return this.lb("previousSibling")},parent:function(){return this.lb("parentNode")},
lb:function(a){return this.map(function(b){for(b=b[a];b&&1!==b.nodeType;)b=b[a];return b||0},Q())},A:function(a,b){var f,c=a;if(b===l&&"string"==typeof a)return b=this[0],!b?p:b===D||b===B?(f=b===D?y.Ec():y.viewport(),"width"==a?f.width:"height"==a?f.height:""):(a=v(a))?z(b,a):p;"string"==typeof a&&(c={},c[a]=b);x&&c.opacity&&(c.filter="alpha(opacity="+100*c.opacity+")",c.zoom=a.zoom||1,delete c.opacity);return this.i(function(a,b,f){for(var g in c)if(c.hasOwnProperty(g)){f=c[g];(b=v(g))&&U.test(f)&&
!(b in t)&&(f=f+R);try{a.style[b]=s(a,f)}catch(d){}}})},d:function(a,b){if(a&&"object"==typeof a&&("number"==typeof a.top||"number"==typeof a.left))return this.i(function(b){k(b,a.left,a.top)});if("number"==typeof a||"number"==typeof b)return this.i(function(f){k(f,a,b)});if(!this[0])return{top:0,left:0,height:0,width:0};var f=this[0],c=f.ownerDocument.documentElement,g=f.getBoundingClientRect(),d=B.pageXOffset||u.scrollLeft,n=f.offsetWidth,f=f.offsetHeight,j=g.top+(B.pageYOffset||u.scrollTop)-Math.max(0,
c&&c.clientTop,D.body.clientTop),c=g.left+d-Math.max(0,c&&c.clientLeft,D.body.clientLeft);return{top:j,left:c,height:f,width:n}},zb:function(){if(!this.length)return{height:0,width:0};var a=this[0],b=9==a.nodeType&&a.documentElement,f;!b&&a.style&&!a.offsetWidth&&!a.offsetHeight?(f={position:a.style.position||"",visibility:a.style.visibility||"",display:a.style.display||""},this.ta().A({position:"absolute",visibility:"hidden",display:"block"})):f=p;var c=b?Math.max(a.body.scrollWidth,a.body.offsetWidth,
b.scrollWidth,b.offsetWidth,b.clientWidth):a.offsetWidth,a=b?Math.max(a.body.scrollHeight,a.body.offsetHeight,b.scrollWidth,b.offsetWidth,b.clientHeight):a.offsetHeight;f&&this.ta().A(f);return{height:a,width:c}},Sa:function(a,b){var c=this[0];if("string"!=typeof a&&!(a instanceof String)){for(var g in a)a.hasOwnProperty(g)&&this.Sa(g,a[g]);return this}return"undefined"==typeof b?!c?p:J.test(a)?j.test(a)&&"string"==typeof c[a]?o:c[a]:("href"==a||"src"==a)&&n.Tc?c[f](a,2):c[f](a):this.i(function(f){J.test(a)?
f[a]=s(f,b):f[T](a,s(f,b))})},data:function(a,b){var f=this[0],g,n;if("undefined"===typeof b){if(!f)return p;g=c(f);if("undefined"===typeof a)return d(f.attributes,function(a){(n=(""+a.name).match(S))&&(g[i(n[1])]=q(a.value))}),g;"undefined"===typeof g[a]&&(g[a]=q(this.Sa("data-"+(a?a.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase():a))));return g[a]}return this.i(function(f){c(f)[a]=b})},remove:function(){this.zc(m);return this.detach()},empty:function(){return this.i(function(a){for(h(a.childNodes,
m);a.firstChild;)a.removeChild(a.firstChild)})},detach:function(){return this.i(function(a){a.parentNode&&a.parentNode.removeChild(a)})},scrollTop:function(a){return F.call(this,p,a,"y")},scrollLeft:function(a){return F.call(this,a,p,"x")}};y.Wb=function(a){L=a;delete y.Wb};y.Qd=function(a,b){for(var f in a)a.hasOwnProperty(f)&&((b||I.prototype)[f]=a[f])};y.create=function(a){return"string"==typeof a&&""!==a?function(){var b=/^\s*<([^\s>]+)/.exec(a),f=D.createElement("div"),c=[],j=b?g[b[1].toLowerCase()]:
p,t=j?j[2]+1:1,z=j&&j[3],h=n.sc&&j&&"<table>"==j[0]&&!/<tbody/i.test(a);for(f.innerHTML=j?j[0]+a+j[1]:a;t--;)f=f.firstChild;z&&(f&&1!==f.nodeType)&&(f=f.nextSibling);do(!b||1==f.nodeType)&&(!h||"tbody"!=f.tagName.toLowerCase())&&c.push(f);while(f=f.nextSibling);d(c,function(a){a.parentNode&&a.parentNode.removeChild(a)});return c}():b(a)?[a.cloneNode(o)]:[]};y.Ec=function(){var a=y.viewport();return{width:Math.max(D.body.scrollWidth,u.scrollWidth,a.width),height:Math.max(D.body.scrollHeight,u.scrollHeight,
a.height)}};y.firstChild=function(a){for(var a=a.childNodes,b=0,f=a&&a.length||0,c;b<f;b++)1===a[b].nodeType&&(c=a[f=b]);return c};y.viewport=function(){return{width:x?u.clientWidth:self.innerWidth,height:x?u.clientHeight:self.innerHeight}};y.ve="compareDocumentPosition"in u?function(a,b){return 16==(a.compareDocumentPosition(b)&16)}:"contains"in u?function(a,b){return a!==b&&a.contains(b)}:function(a,b){for(;b=b.parentNode;)if(b===a)return o;return G};return y},this);provide("bonzo",d.b);(function(d){function h(c){for(var d=
[],e=0,b=0,h,i,k;i=c[e];++e){k=G;for(h=0;h<d.length;++h)if(d[h]===i){k=o;break}k||(d[b++]=i)}return d}var i=require("bonzo");i.Wb(d);d.l(i);d.l(i(),o);d.l({create:function(c){return d(i.create(c))}});d.id=function(c){return d([document.getElementById(c)])};d.l({ed:function(c,i){if(!this.length)return this;c||(c="*");var q=d(c),b,v,r,k=[];b=0;for(v=this.length;b<v;b++)for(r=this[b];r=r.parentNode;){var s;a:{for(s=0;s<q.length;s++)if(q[s]===r)break a;s=-1}if(~s&&(k.push(r),i))break}return d(h(k))},
parent:function(){return d(h(i(this).parent()))},Ud:function(c){return this.ed(c,o)},ta:function(){return d(this.length?this[0]:this)},Pb:function(){return d(this.length?this[this.length-1]:[])},next:function(){return d(i(this).next())},Ba:function(){return d(i(this).Ba())},Ra:function(c){return i(this.O).Ra(c,this)},Rb:function(c){return i(this.O).Rb(c,this)},Lb:function(c){return i(this.O).Lb(c,this)},insertBefore:function(c){return i(this.O).insertBefore(c,this)},gf:function(){var c,h,i,b=[];c=
0;for(h=this.length;c<h;c++){for(i=this[c];i=i.previousSibling;)1==i.nodeType&&b.push(i);for(i=this[c];i=i.nextSibling;)1==i.nodeType&&b.push(i)}return d(b)},children:function(){var c,m,q,b=[];c=0;for(m=this.length;c<m;c++)if(q=i.firstChild(this[c]))for(b.push(q);q=q.nextSibling;)1==q.nodeType&&b.push(q);return d(h(b))},height:function(c){return"undefined"==typeof c?i(this).zb().height:this.A("height",c)},width:function(c){return"undefined"==typeof c?i(this).zb().width:this.A("width",c)}},o)})(ender)})();
(function(){var d={b:{}};!function(e,h){"undefined"!=typeof d?d.b=h():"function"==typeof define&&"object"==typeof define.qc?define(h):this[e]=h()}("domready",function(d){function h(){var b;for(v=1;b=i.shift();)b()}var i=[],c,m=document,q=m.documentElement,b=q.doScroll,v=/^loade|c/.test(m.readyState);m.addEventListener&&m.addEventListener("DOMContentLoaded",c=function(){m.removeEventListener("DOMContentLoaded",c,G);h()},G);b&&m.attachEvent("onreadystatechange",c=function(){/^c/.test(m.readyState)&&
(m.detachEvent("onreadystatechange",c),h())});return d=b?function(b){self!=top?v?b():i.push(b):function(){try{q.doScroll("left")}catch(c){return setTimeout(function(){d(b)},50)}b()}()}:function(b){v?b():i.push(b)}});provide("domready",d.b);!function(d){var h=require("domready");d.l({ce:h});d.l({fd:function(d){h(d);return this}},o)}(ender)})();
(function(){var d={b:{}};(function(e,h,i){"undefined"!=typeof d&&d.b?d.b=h():"function"==typeof i.define&&i.define.amd?define(e,h):i[e]=h()})("qwery",function(){function d(a){"undefined"!==typeof a.useNativeQSA&&(g=!a.useNativeQSA?h:ea?i:h)}function h(b,f){var c=[],g,d,n,j,b=b.replace(S,"$1");if(g=b.match(V)){j=m(g[2]);g=f[A](g[1]||"*");d=0;for(n=g.length;d<n;d++)j.test(g[d].className)&&(c[c.length]=g[d]);return c}q(g=b.split(","),L(f,function(b,g,t){j=w(g,b);d=0;for(n=j.length;d<n;d++)if(9===b[a]||
t||W(j[d],f))c[c.length]=j[d]}));return 1<g.length&&1<c.length?y(c):c}function i(b,f){var c=[],g,d;try{if(9===f[a]||!U.test(b))return v(f.querySelectorAll(b));q(g=b.split(","),L(f,function(a,b){d=a.querySelectorAll(b);1==d.length?c[c.length]=d.item(0):d.length&&(c=c.concat(v(d)))}));return 1<g.length&&1<c.length?y(c):c}catch(n){}return h(b,f)}function c(){this.ra={}}function m(a){return aa.r(a)||aa.t(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function q(a,b){for(var f=0,c=a.length;f<c;f++)b(a[f])}function b(a){for(var b=
[],f=0,c=a.length;f<c;++f)B(a[f])?b=b.concat(a[f]):b[b.length]=a[f];return b}function v(a){for(var b=0,f=a.length,c=[];b<f;b++)c[b]=a[b];return c}function r(b){for(;(b=b.previousSibling)&&1!=b[a];);return b}function k(a){return a.match(M)}function s(b,f,c,g,d,n,t,e,z,h,i){var H,k,M;if(1!==this[a]||f&&"*"!==f&&this[N]&&this[N].toLowerCase()!==f||c&&(H=c.match(j))&&H[1]!==this.id)return G;if(c&&(M=c.match(x)))for(b=M.length;b--;)if(!m(M[b].slice(1)).test(this.className))return G;if(z&&u.Ca[z]&&!u.Ca[z](this,
i))return G;if(g&&!t)for(k in z=this.attributes,z)if(Object.prototype.hasOwnProperty.call(z,k)&&(z[k].name||k)==d)return this;return g&&!E(n,ca(this,d)||"",t)?G:this}function I(a){return ba.r(a)||ba.t(a,a.replace(f,"\\$1"))}function E(a,b,f){switch(a){case "=":return b==f;case "^=":return b.match(P.r("^="+f)||P.t("^="+f,"^"+I(f),1));case "$=":return b.match(P.r("$="+f)||P.t("$="+f,I(f)+"$",1));case "*=":return b.match(P.r(f)||P.t(f,I(f),1));case "~=":return b.match(P.r("~="+f)||P.t("~="+f,"(?:^|\\s+)"+
I(f)+"(?:\\s+|$)",1));case "|=":return b.match(P.r("|="+f)||P.t("|="+f,"^"+I(f)+"(-|$)",1))}return 0}function w(b,f){var c=[],g=[],d,n,j,e,h,i=f,x=Y.r(b)||Y.t(b,b.split(z)),M=b.match(t);if(!x.length)return c;n=(x=x.slice(0)).pop();if(x.length&&(d=x[x.length-1].match(H)))i=D(f,d[1]);if(!i)return c;e=k(n);j=i!==f&&9!==i[a]&&M&&/^[+~]$/.test(M[M.length-1])?function(b){for(;i=i.nextSibling;)1==i[a]&&(e[1]?e[1]==i[N].toLowerCase():1)&&(b[b.length]=i);return b}([]):i[A](e[1]||"*");d=0;for(n=j.length;d<
n;d++)if(h=s.apply(j[d],e))c[c.length]=h;if(!x.length)return c;q(c,function(a){F(a,x,M)&&(g[g.length]=a)});return g}function F(a,b,f,c){function g(a,c,n){for(;n=Z[f[c]](n,a);)if(C(n)&&s.apply(n,k(b[c])))if(c){if(d=g(n,c-1,n))return d}else return n}var d;return(d=g(a,b.length-1,a))&&(!c||W(d,c))}function C(b){var f;return b&&"object"===typeof b&&(f=b[a])&&(1==f||9==f)}function y(a){var b=[],f,c;f=0;a:for(;f<a.length;++f){for(c=0;c<b.length;++c)if(b[c]==a[f])continue a;b[b.length]=a[f]}return b}function B(a){return"object"===
typeof a&&isFinite(a.length)}function D(b,f){var c;return 9===b[a]?b.getElementById(f):b.ownerDocument&&((c=b.ownerDocument.getElementById(f))&&W(c,b)&&c||!W(b,b.ownerDocument)&&g('[id="'+f+'"]',b)[0])}function u(f,c){var d,j,t=!c?J:"string"==typeof c?u(c)[0]:!c[a]&&B(c)?c[0]:c;if(!t||!f)return[];if(f===window||C(f))return!c||f!==window&&C(t)&&W(f,t)?[f]:[];if(f&&B(f))return b(f);if(d=f.match(n)){if(d[1])return(j=D(t,d[1]))?[j]:[];if(d[2])return v(t[A](d[2]));if(da&&d[3])return v(t[K](d[3]))}return g(f,
t)}function L(b,f){return function(c){var g,d;if(U.test(c)){if(9!==b[a]){if(!(d=g=b.getAttribute("id")))b.setAttribute("id",d="__qwerymeupscotty");f(b.parentNode||b,'[id="'+d+'"]'+c,o);g||b.removeAttribute("id")}}else c.length&&f(b,c,G)}}var J=document,O=J.documentElement,K="getElementsByClassName",A="getElementsByTagName",N="tagName",a="nodeType",g,j=/#([\w\-]+)/,x=/\.[\w\-]+/g,H=/^#([\w\-]+)$/,V=/^([\w]+)?\.([\w\-]+)$/,U=/(^|,)\s*[>~+]/,S=/^\s+|\s*([,\s\+\~>]|$)\s*/g,R=/[\s\>\+\~]/,T=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,
f=/([.*+?\^=!:${}()|\[\]\/\\])/g,n=RegExp(H.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),t=RegExp("("+R.source+")"+T.source,"g"),z=RegExp(R.source+T.source),M=RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),Z={" ":function(a){return a&&a!==O&&a.parentNode},">":function(a,b){return a&&a.parentNode==b.parentNode&&a.parentNode},
"~":function(a){return a&&a.previousSibling},"+":function(a,b,f,c){return!a?G:(f=r(a))&&(c=r(b))&&f==c&&f}};c.prototype={r:function(a){return this.ra[a]||l},t:function(a,b,f){b=f?RegExp(b):b;return this.ra[a]=b}};var aa=new c,ba=new c,P=new c,Y=new c,W="compareDocumentPosition"in O?function(a,b){return 16==(b.compareDocumentPosition(a)&16)}:"contains"in O?function(b,f){f=9===f[a]||f==window?O:f;return f!==b&&f.contains(b)}:function(a,b){for(;a=a.parentNode;)if(a===b)return 1;return 0},ca=function(){var a=
J.createElement("p");return(a.innerHTML='<a href="#x">x</a>')&&"#x"!=a.firstChild.getAttribute("href")?function(a,b){return"class"===b?a.className:"href"===b||"src"===b?a.getAttribute(b,2):a.getAttribute(b)}:function(a,b){return a.getAttribute(b)}}(),da=!!J[K],ea=J.querySelector&&J.querySelectorAll;d({xf:o});u.Zd=d;u.Ia=y;u.Nb=function(a,f,c){if(C(f))return a==f;if(B(f))return!!~b(f).indexOf(a);for(var g=f.split(","),d;f=g.pop();)if(d=Y.r(f)||Y.t(f,f.split(z)),f=f.match(t),d=d.slice(0),s.apply(a,
k(d.pop()))&&(!d.length||F(a,d,f,c)))return o;return G};u.Ca={};return u},this);provide("qwery",d.b);(function(d){var h=function(){var d;try{d=require("qwery")}catch(c){d=require("qwery-mobile")}finally{return d}}();d.Ca=h.Ca;d.Oa=function(i,c){return(d.Oa=function(){var c;if("function"==typeof d.create)return function(b,c){return/^\s*</.test(b)?d.create(b,c):h(b,c)};try{return c=require("bonzo"),function(b,d){return/^\s*</.test(b)?c.create(b,d):h(b,d)}}catch(i){}return h}())(i,c)};d.l({find:function(i){var c=
[],m,q,b,v,r;m=0;for(q=this.length;m<q;m++){r=h(i,this[m]);b=0;for(v=r.length;b<v;b++)c.push(r[b])}return d(h.Ia(c))},Pd:function(h){for(var h=d(h),c=this.length,m=0,q=this.length+h.length;c<q;c++,m++)this[c]=h[m];this.length+=h.length;return this},Nb:function(d,c){var e,q;e=0;for(q=this.length;e<q;e++)if(h.Nb(this[e],d,c))return o;return G}},o)})(ender)})();
(function(){var d={b:{}},e=d.b;(function(){function h(a,c,d,g){if(a===c)return 0!==a||1/a==1/c;if(a==p||c==p)return a===c;a instanceof b&&(a=a.U);c instanceof b&&(c=c.U);var j=C.call(a);if(j!=C.call(c))return G;switch(j){case "[object String]":return a==""+c;case "[object Number]":return a!=+a?c!=+c:0==a?1/a==1/c:a==+c;case "[object Date]":case "[object Boolean]":return+a==+c;case "[object RegExp]":return a.source==c.source&&a.global==c.global&&a.multiline==c.multiline&&a.ignoreCase==c.ignoreCase}if("object"!=
typeof a||"object"!=typeof c)return G;for(var e=d.length;e--;)if(d[e]==a)return g[e]==c;d.push(a);g.push(c);var e=0,i=o;if("[object Array]"==j){if(e=a.length,i=e==c.length)for(;e--&&(i=h(a[e],c[e],d,g)););}else{var j=a.constructor,x=c.constructor;if(j!==x&&(!b.s(j)||!(j instanceof j&&b.s(x)&&x instanceof x)))return G;for(var H in a)if(b.c(a,H)&&(e++,!(i=b.c(c,H)&&h(a[H],c[H],d,g))))break;if(i){for(H in c)if(b.c(c,H)&&!e--)break;i=!e}}d.pop();g.pop();return i}function i(){}function c(a,d,g){j(a,function(a){b.isArray(a)?
d?E.apply(g,a):c(a,d,g):g.push(a)});return g}function m(a,b,c,d){var g={},e=q(b);j(a,function(b,j){var n=e.call(c,b,j,a);d(g,n,b)});return g}function q(a){return b.s(a)?a:function(b){return b[a]}}function b(a){if(a instanceof b)return a;if(!(this instanceof b))return new b(a);this.U=a}var v=this,r=v.R,k={},s=Array.prototype,I=Object.prototype,E=s.push,w=s.slice,F=s.concat,C=I.toString,y=I.hasOwnProperty,B=s.forEach,D=s.map,u=s.reduce,L=s.reduceRight,J=s.filter,O=s.every,K=s.some,A=s.indexOf,N=s.lastIndexOf,
I=Array.isArray,a=Object.keys,g=Function.prototype.bind;"undefined"!==typeof e?("undefined"!==typeof d&&d.b&&(e=d.b=b),e.R=b):v._=b;b.VERSION="1.4.2";var j=b.i=b.forEach=function(a,c,d){if(a!=p)if(B&&a.forEach===B)a.forEach(c,d);else if(a.length===+a.length)for(var g=0,j=a.length;g<j;g++){if(c.call(d,a[g],g,a)===k)break}else for(g in a)if(b.c(a,g)&&c.call(d,a[g],g,a)===k)break};b.map=b.Xd=function(a,b,c){var d=[];if(a==p)return d;if(D&&a.map===D)return a.map(b,c);j(a,function(a,f,g){d[d.length]=b.call(c,
a,f,g)});return d};b.reduce=b.je=b.se=function(a,c,d,g){var e=arguments.length>2;a==p&&(a=[]);if(u&&a.reduce===u){g&&(c=b.bind(c,g));return e?a.reduce(c,d):a.reduce(c)}j(a,function(a,b,f){if(e)d=c.call(g,d,a,b,f);else{d=a;e=o}});if(!e)throw new TypeError("Reduce of empty array with no initial value");return d};b.reduceRight=b.ke=function(a,c,d,g){var e=arguments.length>2;a==p&&(a=[]);if(L&&a.reduceRight===L){g&&(c=b.bind(c,g));return arguments.length>2?a.reduceRight(c,d):a.reduceRight(c)}var h=a.length;
if(h!==+h)var i=b.keys(a),h=i.length;j(a,function(b,j,x){j=i?i[--h]:--h;if(e)d=c.call(g,d,a[j],j,x);else{d=a[j];e=o}});if(!e)throw new TypeError("Reduce of empty array with no initial value");return d};b.find=b.be=function(a,b,c){var d;x(a,function(a,f,g){if(b.call(c,a,f,g)){d=a;return o}});return d};b.filter=b.select=function(a,b,c){var d=[];if(a==p)return d;if(J&&a.filter===J)return a.filter(b,c);j(a,function(a,f,g){b.call(c,a,f,g)&&(d[d.length]=a)});return d};b.Ze=function(a,b,c){var d=[];if(a==
p)return d;j(a,function(a,f,g){b.call(c,a,f,g)||(d[d.length]=a)});return d};b.every=b.all=function(a,c,d){c||(c=b.wa);var g=o;if(a==p)return g;if(O&&a.every===O)return a.every(c,d);j(a,function(a,b,f){if(!(g=g&&c.call(d,a,b,f)))return k});return!!g};var x=b.some=b.rc=function(a,c,d){c||(c=b.wa);var g=G;if(a==p)return g;if(K&&a.some===K)return a.some(c,d);j(a,function(a,b,f){if(g||(g=c.call(d,a,b,f)))return k});return!!g};b.contains=b.qe=function(a,b){var c=G;if(a==p)return c;if(A&&a.indexOf===A)return a.indexOf(b)!=
-1;return c=x(a,function(a){return a===b})};b.ue=function(a,c){var d=w.call(arguments,2);return b.map(a,function(a){return(b.s(c)?c:a[c]).apply(a,d)})};b.Aa=function(a,c){return b.map(a,function(a){return a[c]})};b.yd=function(a,c){return b.Z(c)?[]:b.filter(a,function(a){for(var b in c)if(c[b]!==a[b])return G;return o})};b.max=function(a,c,d){if(!c&&b.isArray(a)&&a[0]===+a[0]&&a.length<65535)return Math.max.apply(Math,a);if(!c&&b.Z(a))return-Infinity;var g={da:-Infinity};j(a,function(a,b,f){b=c?c.call(d,
a,b,f):a;b>=g.da&&(g={value:a,da:b})});return g.value};b.min=function(a,c,d){if(!c&&b.isArray(a)&&a[0]===+a[0]&&a.length<65535)return Math.min.apply(Math,a);if(!c&&b.Z(a))return Infinity;var g={da:Infinity};j(a,function(a,b,f){b=c?c.call(d,a,b,f):a;b<g.da&&(g={value:a,da:b})});return g.value};b.ff=function(a){var c,d=0,g=[];j(a,function(a){c=b.random(d++);g[d-1]=g[c];g[c]=a});return g};b.od=function(a){var c=q(l);return b.Aa(b.map(a,function(a,b,f){return{value:a,index:b,wb:c.call(l,a,b,f)}}).sort(function(a,
b){var c=a.wb,f=b.wb;if(c!==f){if(c>f||c===l)return 1;if(c<f||f===l)return-1}return a.index<b.index?-1:1}),"value")};b.le=function(a,c,d){return m(a,c,d,function(a,c,f){(b.c(a,c)?a[c]:a[c]=[]).push(f)})};b.$d=function(a,c,d){return m(a,c,d,function(a,c){b.c(a,c)||(a[c]=0);a[c]++})};b.pd=function(a,c){var d;d=d==p?b.wa:q(d);for(var g=d.call(l,c),j=0,e=a.length;j<e;){var h=j+e>>>1;d.call(l,a[h])<g?j=h+1:e=h}return j};b.vd=function(a){return!a?[]:a.length===+a.length?w.call(a):b.wd(a)};b.size=function(a){return a.length===
+a.length?a.length:b.keys(a).length};b.ta=b.head=b.jf=function(a,b,c){return b!=p&&!c?w.call(a,0,b):a[0]};b.re=function(a,b,c){return w.call(a,0,a.length-(b==p||c?1:b))};b.Pb=function(a,b,c){return b!=p&&!c?w.call(a,Math.max(a.length-b,0)):a[a.length-1]};b.bf=b.ja=b.de=function(a,b,c){return w.call(a,b==p||c?1:b)};b.compact=function(a){return b.filter(a,function(a){return!!a})};b.he=function(a,b){return c(a,b,[])};b.zf=function(a){return b.Dc(a,w.call(arguments,1))};b.Ia=b.unique=function(a,c,d,g){var d=
d?b.map(a,d,g):a,e=[],h=[];j(d,function(d,g){if(c?!g||h[h.length-1]!==d:!b.contains(h,d)){h.push(d);e.push(a[g])}});return e};b.vf=function(){return b.Ia(F.apply(s,arguments))};b.te=function(a){var c=w.call(arguments,1);return b.filter(b.Ia(a),function(a){return b.every(c,function(c){return b.indexOf(c,a)>=0})})};b.Dc=function(a){var c=F.apply(s,w.call(arguments,1));return b.filter(a,function(a){return!b.contains(c,a)})};b.Bf=function(){for(var a=w.call(arguments),c=b.max(b.Aa(a,"length")),d=Array(c),
g=0;g<c;g++)d[g]=b.Aa(a,""+g);return d};b.object=function(a,b){for(var c={},d=0,g=a.length;d<g;d++)b?c[a[d]]=b[d]:c[a[d][0]]=a[d][1];return c};b.indexOf=function(a,c,d){if(a==p)return-1;var g=0,j=a.length;if(d)if(typeof d=="number")g=d<0?Math.max(0,j+d):d;else{g=b.pd(a,c);return a[g]===c?g:-1}if(A&&a.indexOf===A)return a.indexOf(c,d);for(;g<j;g++)if(a[g]===c)return g;return-1};b.lastIndexOf=function(a,b,c){if(a==p)return-1;var d=c!=p;if(N&&a.lastIndexOf===N)return d?a.lastIndexOf(b,c):a.lastIndexOf(b);
for(c=d?c:a.length;c--;)if(a[c]===b)return c;return-1};b.Ye=function(a,b,c){if(arguments.length<=1){b=a||0;a=0}for(var c=arguments[2]||1,d=Math.max(Math.ceil((b-a)/c),0),g=0,j=Array(d);g<d;){j[g++]=a;a=a+c}return j};b.bind=function(a,c){var d,j;if(a.bind===g&&g)return g.apply(a,w.call(arguments,1));if(!b.s(a))throw new TypeError;j=w.call(arguments,2);return d=function(){if(!(this instanceof d))return a.apply(c,j.concat(w.call(arguments)));i.prototype=a.prototype;var b=new i,g=a.apply(b,j.concat(w.call(arguments)));
return Object(g)===g?g:b}};b.tc=function(a){var c=w.call(arguments,1);c.length==0&&(c=b.Db(a));j(c,function(c){a[c]=b.bind(a[c],a)})};b.Ie=function(a,c){var d={};c||(c=b.wa);return function(){var g=c.apply(this,arguments);return b.c(d,g)?d[g]:d[g]=a.apply(this,arguments)}};b.Bc=function(a,b){var c=w.call(arguments,2);return setTimeout(function(){return a.apply(p,c)},b)};b.defer=function(a){return b.Bc.apply(b,[a,1].concat(w.call(arguments,1)))};b.rf=function(a,c){var d,g,j,e,h,i,x=b.yc(function(){h=
e=G},c);return function(){d=this;g=arguments;j||(j=setTimeout(function(){j=p;h&&(i=a.apply(d,g));x()},c));if(e)h=o;else{e=o;i=a.apply(d,g)}x();return i}};b.yc=function(a,b){var c,d;return function(){var g=this,j=arguments;clearTimeout(c);c=setTimeout(function(){c=p;d=a.apply(g,j)},b);return d}};b.Oe=function(a){var b=G,c;return function(){if(b)return c;b=o;c=a.apply(this,arguments);a=p;return c}};b.Af=function(a,b){return function(){var c=[a];E.apply(c,arguments);return b.apply(this,c)}};b.Yd=function(){var a=
arguments;return function(){for(var b=arguments,c=a.length-1;c>=0;c--)b=[a[c].apply(this,b)];return b[0]}};b.pc=function(a,b){return a<=0?b():function(){if(--a<1)return b.apply(this,arguments)}};b.keys=a||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var c=[],d;for(d in a)b.c(a,d)&&(c[c.length]=d);return c};b.wd=function(a){var c=[],d;for(d in a)b.c(a,d)&&c.push(a[d]);return c};b.Se=function(a){var c=[],d;for(d in a)b.c(a,d)&&c.push([d,a[d]]);return c};b.Xc=function(a){var c=
{},d;for(d in a)b.c(a,d)&&(c[a[d]]=d);return c};b.Db=b.Je=function(a){var c=[],d;for(d in a)b.s(a[d])&&c.push(d);return c.sort()};b.extend=function(a){j(w.call(arguments,1),function(b){for(var c in b)a[c]=b[c]});return a};b.Ue=function(a){var b={},c=F.apply(s,w.call(arguments,1));j(c,function(c){c in a&&(b[c]=a[c])});return b};b.Ne=function(a){var c={},d=F.apply(s,w.call(arguments,1)),g;for(g in a)b.contains(d,g)||(c[g]=a[g]);return c};b.Ac=function(a){j(w.call(arguments,1),function(b){for(var c in b)a[c]==
p&&(a[c]=b[c])});return a};b.h=function(a){return!b.hb(a)?a:b.isArray(a)?a.slice():b.extend({},a)};b.kf=function(a,b){b(a);return a};b.isEqual=function(a,b){return h(a,b,[],[])};b.Z=function(a){if(a==p)return o;if(b.isArray(a)||b.Ce(a))return a.length===0;for(var c in a)if(b.c(a,c))return G;return o};b.xe=function(a){return!!(a&&a.nodeType===1)};b.isArray=I||function(a){return C.call(a)=="[object Array]"};b.hb=function(a){return a===Object(a)};j("Arguments Function String Number Date RegExp".split(" "),
function(a){b["is"+a]=function(b){return C.call(b)=="[object "+a+"]"}});b.Yc(arguments)||(b.Yc=function(a){return!(!a||!b.c(a,"callee"))});"function"!==typeof/./&&(b.s=function(a){return typeof a==="function"});b.ye=function(a){return b.Zc(a)&&isFinite(a)};b.ze=function(a){return b.Zc(a)&&a!=+a};b.we=function(a){return a===o||a===G||C.call(a)=="[object Boolean]"};b.Ae=function(a){return a===p};b.De=function(a){return a===l};b.c=function(a,b){return y.call(a,b)};b.kb=function(){v.R=r;return this};
b.wa=Q();b.sf=function(a,b,c){for(var d=0;d<a;d++)b.call(c,d)};b.random=function(a,b){if(b==p){b=a;a=0}return a+(0|Math.random()*(b-a+1))};var H={escape:{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"}};H.unescape=b.Xc(H.escape);var V={escape:RegExp("["+b.keys(H.escape).join("")+"]","g"),unescape:RegExp("("+b.keys(H.unescape).join("|")+")","g")};b.i(["escape","unescape"],function(a){b[a]=function(b){return b==p?"":(""+b).replace(V[a],function(b){return H[a][b]})}});b.result=
function(a,c){if(a==p)return p;var d=a[c];return b.s(d)?d.call(a):d};b.bd=function(a){j(b.Db(a),function(c){var d=b[c]=a[c];b.prototype[c]=function(){var a=[this.U];E.apply(a,arguments);a=d.apply(b,a);return this.Ma?b(a).K():a}})};var U=0;b.cc=function(a){var b=U++;return a?a+b:b};b.ud={evaluate:/<%([\s\S]+?)%>/g,Wc:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var S=/(.)^/,R={"'":"'","\\":"\\","\r":"r","\n":"n","\t":"t","\u2028":"u2028","\u2029":"u2029"},T=/\\|'|\r|\n|\t|\u2028|\u2029/g;b.nf=function(a,
c,d){function g(a){return h.call(this,a,b)}var d=b.Ac({},d,b.ud),j=0,e="__p+='";a.replace(RegExp([(d.escape||S).source,(d.Wc||S).source,(d.evaluate||S).source].join("|")+"|$","g"),function(b,c,d,g,h){e=e+a.slice(j,h).replace(T,function(a){return"\\"+R[a]});e=e+(c?"'+\n((__t=("+c+"))==null?'':_.escape(__t))+\n'":d?"'+\n((__t=("+d+"))==null?'':__t)+\n'":g?"';\n"+g+"\n__p+='":"");j=h+b.length});e=e+"';\n";d.ec||(e="with(obj||{}){\n"+e+"}\n");e="var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};\n"+
e+"return __p;\n";try{var h=new Function(d.ec||"obj","_",e)}catch(i){i.source=e;throw i;}if(c)return h(c,b);g.source="function("+(d.ec||"obj")+"){\n"+e+"}";return g};b.K=function(a){return b(a).K()};b.bd(b);j("pop push reverse shift sort splice unshift".split(" "),function(a){var c=s[a];b.prototype[a]=function(){var d=this.U;c.apply(d,arguments);(a=="shift"||a=="splice")&&d.length===0&&delete d[0];return this.Ma?b(d).K():d}});j(["concat","join","slice"],function(a){var c=s[a];b.prototype[a]=function(){var a=
c.apply(this.U,arguments);return this.Ma?b(a).K():a}});b.extend(b.prototype,{K:function(){this.Ma=o;return this},value:function(){return this.U}})}).call(this);provide("underscore",d.b);$.l(d.b)})();
(function(){var d={};(function(){function e(){throw Error('A "url" property or function must be specified');}function h(a,b){return!a||!a[b]?p:k.s(a[b])?a[b]():a[b]}function i(a,b,d){var e;e=b&&b.hasOwnProperty("constructor")?b.constructor:function(){a.apply(this,arguments)};k.extend(e,a);c.prototype=a.prototype;e.prototype=new c;b&&k.extend(e.prototype,b);d&&k.extend(e,d);e.prototype.constructor=e;e.Ld=a.prototype;return e}function c(){}var m=this,q=m.ob,b=Array.prototype.slice,v=Array.prototype.splice,
r;r="undefined"!==typeof d?d:m.ob={};r.VERSION="0.9.2";var k=m.R;!k&&"undefined"!==typeof require&&(k=require("underscore"));var s=m.Fe||m.Kd||m.l;r.ef=function(a){s=a};r.kb=function(){m.ob=q;return this};r.Hc=G;r.Wa=G;var I=/\s+/,E=r.Fd={N:function(a,b,c){var d,e,h,i,k;if(!b)return this;a=a.split(I);for(d=this.ma||(this.ma={});e=a.shift();)h=(k=d[e])?k.ja:{},h.next=i={},h.Va=c,h.o=b,d[e]={ja:i,next:k?k.next:h};return this},ya:function(a,b,c){var d,e,h,i,m,q;if(e=this.ma){if(!a&&!b&&!c)return delete this.ma,
this;for(a=a?a.split(I):k.keys(e);d=a.shift();)if(h=e[d],delete e[d],h&&(b||c))for(i=h.ja;(h=h.next)!==i;)m=h.o,q=h.Va,(b&&m!==b||c&&q!==c)&&this.N(d,m,q);return this}},f:function(a){var c,d,e,h,i,k;if(!(e=this.ma))return this;i=e.all;a=a.split(I);for(k=b.call(arguments,1);c=a.shift();){if(d=e[c])for(h=d.ja;(d=d.next)!==h;)d.o.apply(d.Va||this,k);if(d=i){h=d.ja;for(c=[c].concat(k);(d=d.next)!==h;)d.o.apply(d.Va||this,c)}}return this}};E.bind=E.N;E.Ha=E.ya;var w=r.Hd=function(a,b){var c;a||(a={});
b&&b.parse&&(a=this.parse(a));if(c=h(this,"defaults"))a=k.extend({},c,a);b&&b.q&&(this.q=b.q);this.attributes={};this.Na={};this.z=k.cc("c");this.p={};this.J={};this.w={};this.set(a,{k:o});this.p={};this.J={};this.w={};this.T=k.h(this.attributes)};k.extend(w.prototype,E,{p:p,J:p,w:p,va:"id",bb:X(),toJSON:function(){return k.h(this.attributes)},get:function(a){return this.attributes[a]},escape:function(a){var b;if(b=this.Na[a])return b;b=this.get(a);return this.Na[a]=k.escape(b==p?"":""+b)},c:function(a){return this.get(a)!=
p},set:function(a,b,c){var d,e;k.hb(a)||a==p?(d=a,c=b):(d={},d[a]=b);c||(c={});if(!d)return this;d instanceof w&&(d=d.attributes);if(c.ka)for(e in d)d[e]=l;if(!this.Pa(d,c))return G;this.va in d&&(this.id=d[this.va]);var b=c.vc={},h=this.attributes,i=this.Na,m=this.T||{};for(e in d){a=d[e];if(!k.isEqual(h[e],a)||c.ka&&k.c(h,e))delete i[e],(c.k?this.J:b)[e]=o;c.ka?delete h[e]:h[e]=a;!k.isEqual(m[e],a)||k.c(h,e)!=k.c(m,e)?(this.p[e]=a,c.k||(this.w[e]=o)):(delete this.p[e],delete this.w[e])}c.k||this.sa(c);
return this},ka:function(a,b){(b||(b={})).ka=o;return this.set(a,p,b)},clear:function(a){(a||(a={})).ka=o;return this.set(k.h(this.attributes),a)},Kc:function(a){var a=a?k.h(a):{},b=this,c=a.u;a.u=function(d,e,h){if(!b.set(b.parse(d,h),a))return G;c&&c(b,d)};a.error=r.Ja(a.error,b,a);return(this.G||r.G).call(this,"read",this,a)},save:function(a,b,c){var d,e;k.hb(a)||a==p?(d=a,c=b):(d={},d[a]=b);c=c?k.h(c):{};if(c.H){if(!this.Pa(d,c))return G;e=k.h(this.attributes)}a=k.extend({},c,{k:o});if(d&&!this.set(d,
c.H?a:c))return G;var h=this,i=c.u;c.u=function(a,b,g){b=h.parse(a,g);if(c.H){delete c.H;b=k.extend(d||{},b)}if(!h.set(b,c))return G;i?i(h,a):h.f("sync",h,a,c)};c.error=r.Ja(c.error,h,c);b=(this.G||r.G).call(this,this.gb()?"create":"update",this,c);c.H&&this.set(e,a);return b},ae:function(a){function b(){c.f("destroy",c,c.q,a)}var a=a?k.h(a):{},c=this,d=a.u;if(this.gb())return b(),G;a.u=function(e){a.H&&b();d?d(c,e):c.f("sync",c,e,a)};a.error=r.Ja(a.error,c,a);var e=(this.G||r.G).call(this,"delete",
this,a);a.H||b();return e},url:function(){var a=h(this,"urlRoot")||h(this.q,"url")||e();return this.gb()?a:a+("/"==a.charAt(a.length-1)?"":"/")+encodeURIComponent(this.id)},parse:Q(),h:function(){return new this.constructor(this.attributes)},gb:function(){return this.id==p},sa:function(a){a||(a={});var b=this.pb;this.pb=o;for(var c in this.J)this.w[c]=o;var d=k.extend({},a.vc,this.J);this.J={};for(c in d)this.f("change:"+c,this,this.get(c),a);if(b)return this;for(;!k.Z(this.w);){this.w={};this.f("change",
this,a);for(c in this.p)!this.w[c]&&!this.J[c]&&delete this.p[c];this.T=k.h(this.attributes)}this.pb=G;return this},Pc:function(a){return!arguments.length?!k.Z(this.p):k.c(this.p,a)},Td:function(a){if(!a)return this.Pc()?k.h(this.p):G;var b,c=G,d=this.T,e;for(e in a)if(!k.isEqual(d[e],b=a[e]))(c||(c={}))[e]=b;return c},Ba:function(a){return!arguments.length||!this.T?p:this.T[a]},We:function(){return k.h(this.T)},Ee:function(){return!this.dc(this.attributes)},Pa:function(a,b){if(b.k||!this.dc)return o;
var a=k.extend({},this.attributes,a),c=this.dc(a,b);if(!c)return o;b&&b.error?b.error(this,c,b):this.f("error",this,c,b);return G}});var F=r.Ed=function(a,b){b||(b={});b.fa&&(this.fa=b.fa);b.V&&(this.V=b.V);this.sb();a&&this.reset(a,{k:o,parse:b.parse})};k.extend(F.prototype,E,{fa:w,bb:X(),toJSON:function(a){return this.map(function(b){return b.toJSON(a)})},add:function(a,b){var c,d,e,h,i,m={},q={},r=[];b||(b={});a=k.isArray(a)?a.slice():[a];c=0;for(d=a.length;c<d;c++){if(!(e=a[c]=this.na(a[c],b)))throw Error("Can't add an invalid model to a collection");
h=e.z;i=e.id;m[h]||this.la[h]||i!=p&&(q[i]||this.S[i])?r.push(c):m[h]=q[i]=e}for(c=r.length;c--;)a.splice(r[c],1);c=0;for(d=a.length;c<d;c++)(e=a[c]).N("all",this.qb,this),this.la[e.z]=e,e.id!=p&&(this.S[e.id]=e);this.length+=d;v.apply(this.j,[b.ba!=p?b.ba:this.j.length,0].concat(a));this.V&&this.sort({k:o});if(b.k)return this;c=0;for(d=this.j.length;c<d;c++)if(m[(e=this.j[c]).z])b.index=c,e.f("add",e,this,b);return this},remove:function(a,b){var c,d,e,h;b||(b={});a=k.isArray(a)?a.slice():[a];c=0;
for(d=a.length;c<d;c++)if(h=this.Lc(a[c])||this.get(a[c]))delete this.S[h.id],delete this.la[h.z],e=this.indexOf(h),this.j.splice(e,1),this.length--,b.k||(b.index=e,h.f("remove",h,this,b)),this.rb(h);return this},push:function(a,b){a=this.na(a,b);this.add(a,b);return a},pop:function(a){var b=this.ba(this.length-1);this.remove(b,a);return b},unshift:function(a,b){a=this.na(a,b);this.add(a,k.extend({ba:0},b));return a},shift:function(a){var b=this.ba(0);this.remove(b,a);return b},get:function(a){return a==
p?l:this.S[a.id!=p?a.id:a]},Lc:function(a){return a&&this.la[a.z||a]},ba:function(a){return this.j[a]},yd:function(a){return k.Z(a)?[]:this.filter(function(b){for(var c in a)if(a[c]!==b.get(c))return G;return o})},sort:function(a){a||(a={});if(!this.V)throw Error("Cannot sort a set without a comparator");var b=k.bind(this.V,this);1==this.V.length?this.j=this.od(b):this.j.sort(b);a.k||this.f("reset",this,a);return this},Aa:function(a){return k.map(this.j,function(b){return b.get(a)})},reset:function(a,
b){a||(a=[]);b||(b={});for(var c=0,d=this.j.length;c<d;c++)this.rb(this.j[c]);this.sb();this.add(a,k.extend({k:o},b));b.k||this.f("reset",this,b);return this},Kc:function(a){a=a?k.h(a):{};a.parse===l&&(a.parse=o);var b=this,c=a.u;a.u=function(d,e,h){b[a.add?"add":"reset"](b.parse(d,h),a);c&&c(b,d)};a.error=r.Ja(a.error,b,a);return(this.G||r.G).call(this,"read",this,a)},create:function(a,b){var c=this,b=b?k.h(b):{},a=this.na(a,b);if(!a)return G;b.H||c.add(a,b);var d=b.u;b.u=function(e,h){b.H&&c.add(e,
b);d?d(e,h):e.f("sync",a,h,b)};a.save(p,b);return a},parse:Q(),K:function(){return k(this.j).K()},sb:function(){this.length=0;this.j=[];this.S={};this.la={}},na:function(a,b){b||(b={});a instanceof w?a.q||(a.q=this):(b.q=this,a=new this.fa(a,b),a.Pa(a.attributes,b)||(a=G));return a},rb:function(a){this==a.q&&delete a.q;a.ya("all",this.qb,this)},qb:function(a,b,c,d){("add"==a||"remove"==a)&&c!=this||("destroy"==a&&this.remove(b,d),b&&a==="change:"+b.va&&(delete this.S[b.Ba(b.va)],this.S[b.id]=b),this.f.apply(this,
arguments))}});k.i("forEach each map reduce reduceRight find detect filter select reject every all some any include contains invoke max min sortBy sortedIndex toArray size first initial rest last without indexOf shuffle lastIndexOf isEmpty groupBy".split(" "),function(a){F.prototype[a]=function(){return k[a].apply(k,[this.j].concat(k.vd(arguments)))}});var C=r.Id=function(a){a||(a={});a.ia&&(this.ia=a.ia);this.ic()},y=/:\w+/g,B=/\*\w+/g,D=/[-[\]{}()+?.,\\^$|#\s]/g;k.extend(C.prototype,E,{bb:X(),ha:function(a,
b,c){r.history||(r.history=new u);k.Be(a)||(a=this.nc(a));c||(c=this[b]);r.history.ha(a,k.bind(function(d){d=this.mc(a,d);c&&c.apply(this,d);this.f.apply(this,["route:"+b].concat(d));r.history.f("route",this,b,d)},this));return this},navigate:function(a,b){r.history.navigate(a,b)},ic:function(){if(this.ia){var a=[],b;for(b in this.ia)a.unshift([b,this.ia[b]]);b=0;for(var c=a.length;b<c;b++)this.ha(a[b][0],a[b][1],this[a[b][1]])}},nc:function(a){a=a.replace(D,"\\$&").replace(y,"([^/]+)").replace(B,
"(.*?)");return RegExp("^"+a+"$")},mc:function(a,b){return a.exec(b).slice(1)}});var u=r.Gd=function(){this.Jb=[];k.tc(this,"checkUrl")},L=/^[#\/]/,J=/msie [\w.]+/;u.Ea=G;k.extend(u.prototype,E,{Mb:50,ea:function(a){return(a=(a?a.location:window.location).href.match(/#(.*)$/))?a[1]:""},X:function(a,b){if(a==p)if(this.aa||b){var a=window.location.pathname,c=window.location.search;c&&(a+=c)}else a=this.ea();a.indexOf(this.options.root)||(a=a.substr(this.options.root.length));return a.replace(L,"")},
start:function(a){if(u.Ea)throw Error("Backbone.history has already been started");u.Ea=o;this.options=k.extend({},{root:"/"},this.options,a);this.oa=this.options.me!==G;this.ub=!!this.options.pushState;this.aa=!(!this.options.pushState||!window.history||!window.history.pushState);var a=this.X(),b=document.documentMode;if(b=J.exec(navigator.userAgent.toLowerCase())&&(!b||7>=b))this.M=s('<iframe src="javascript:0" tabindex="-1" />').Rc().Ra("body")[0].contentWindow,this.navigate(a);this.aa?s(window).bind("popstate",
this.ca):this.oa&&"onhashchange"in window&&!b?s(window).bind("hashchange",this.ca):this.oa&&(this.jc=setInterval(this.ca,this.Mb));this.m=a;a=window.location;b=a.pathname==this.options.root;if(this.oa&&this.ub&&!this.aa&&!b)return this.m=this.X(p,o),window.location.replace(this.options.root+"#"+this.m),o;this.ub&&(this.aa&&b&&a.hash)&&(this.m=this.ea().replace(L,""),window.history.replaceState({},document.title,a.protocol+"//"+a.host+this.options.root+this.m));if(!this.options.k)return this.xa()},
stop:function(){s(window).Ha("popstate",this.ca).Ha("hashchange",this.ca);clearInterval(this.jc);u.Ea=G},ha:function(a,b){this.Jb.unshift({ha:a,o:b})},ca:function(){var a=this.X();a==this.m&&this.M&&(a=this.X(this.ea(this.M)));if(a==this.m)return G;this.M&&this.navigate(a);this.xa()||this.xa(this.ea())},xa:function(a){var b=this.m=this.X(a);return k.rc(this.Jb,function(a){if(a.ha.test(b))return a.o(b),o})},navigate:function(a,b){if(!u.Ea)return G;if(!b||b===o)b={f:b};var c=(a||"").replace(L,"");this.m!=
c&&(this.aa?(0!=c.indexOf(this.options.root)&&(c=this.options.root+c),this.m=c,window.history[b.replace?"replaceState":"pushState"]({},document.title,c)):this.oa?(this.m=c,this.tb(window.location,c,b.replace),this.M&&c!=this.X(this.ea(this.M))&&(b.replace||this.M.document.open().close(),this.tb(this.M.location,c,b.replace))):window.location.assign(this.options.root+a),b.f&&this.xa(a))},tb:function(a,b,c){c?a.replace(a.toString().replace(/(javascript:|#).*$/,"")+"#"+b):a.hash=b}});var O=r.Jd=function(a){this.z=
k.cc("view");this.kc(a||{});this.lc();this.yb()},K=/^(\S+)\s*(.*)$/,A="model collection el id attributes className tagName".split(" ");k.extend(O.prototype,E,{tagName:"div",Q:function(a){return this.I.find(a)},bb:X(),af:function(){return this},remove:function(){this.I.remove();return this},ad:function(a,b,c){a=document.createElement(a);b&&s(a).Sa(b);c&&s(a).Vc(c);return a},Ub:function(a,b){this.I&&this.bc();this.I=a instanceof s?a:s(a);this.Bb=this.I[0];b!==G&&this.yb();return this},yb:function(a){if(a||
(a=h(this,"events"))){this.bc();for(var b in a){var c=a[b];k.s(c)||(c=this[a[b]]);if(!c)throw Error('Method "'+a[b]+'" does not exist');var d=b.match(K),e=d[1],d=d[2],c=k.bind(c,this),e=e+(".delegateEvents"+this.z);""===d?this.I.bind(e,c):this.I.Cc(d,e,c)}}},bc:function(){this.I.Ha(".delegateEvents"+this.z)},kc:function(a){this.options&&(a=k.extend({},this.options,a));for(var b=0,c=A.length;b<c;b++){var d=A[b];a[d]&&(this[d]=a[d])}this.options=a},lc:function(){if(this.Bb)this.Ub(this.Bb,G);else{var a=
h(this,"attributes")||{};this.id&&(a.id=this.id);this.className&&(a["class"]=this.className);this.Ub(this.ad(this.tagName,a),G)}}});w.extend=F.extend=C.extend=O.extend=function(a,b){var c=i(this,a,b);c.extend=this.extend;return c};var N={create:"POST",update:"PUT","delete":"DELETE",read:"GET"};r.G=function(a,b,c){var d=N[a];c||(c={});var i={type:d,dataType:"json"};c.url||(i.url=h(b,"url")||e());if(!c.data&&b&&("create"==a||"update"==a))i.contentType="application/json",i.data=JSON.stringify(b.toJSON());
r.Wa&&(i.contentType="application/x-www-form-urlencoded",i.data=i.data?{fa:i.data}:{});if(r.Hc&&("PUT"===d||"DELETE"===d))r.Wa&&(i.data.Md=d),i.type="POST",i.Rd=function(a){a.setRequestHeader("X-HTTP-Method-Override",d)};"GET"!==i.type&&!r.Wa&&(i.Xe=G);return s.Od(k.extend(i,c))};r.Ja=function(a,b,c){return function(d,e){e=d===b?e:d;a?a(b,e,c):b.f("error",b,e,c)}}}).call(this);provide("backbone",d);$.l(d)})();$(document).fd(function(){return window.hf=$("#ender-slider").Gc({$b:G,P:361,speed:100,Da:o,pa:function(d){return console.log(360*d)}})});
window.color={cb:function(d){var e,d=(e=d.match(/^(#)?([0-9a-fA-F]{3})([0-9a-fA-F]{3})?$/))!=p?e.slice(2):l;if(d==p)return G;d=$.R.compact(d).join("");if(6!==d.length){var h,i,c;c=[];h=0;for(i=d.length;h<i;h++)e=d[h],c.push(e+e);d=c.join("")}return"#"+d},ib:function(d){var e,d=(e=d.match(/rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,?\s*(0?\.?\d{1,2})?\s*\)$/))!=p?e.slice(1):l;if(d==p)return G;var h,i,c;i=$.R.compact(d);c=[];d=0;for(h=i.length;d<h;d++)e=i[d],c.push(parseFloat(e));3===c.length&&
c.push(1);return 255>=c[0]&&255>=c[1]&&255>=c[2]&&1>=(c[3]!=p)?c:G},eb:function(d){var e,d=(e=d.match(/hsla?\(\s*(\d{1,3})\s*,\s*(\d{1,3}\%)\s*,\s*(\d{1,3}\%)\s*,?\s*(\.?\d{1,2})?\s*\)$/))!=p?e.slice(1):l;return d!=p?(e=$.R.compact(d),3===e.length&&e.push(1),(d=360>=parseInt(e[0])&&100>=parseInt(e[1])&&100>=parseInt(e[2])&&1>=parseFloat(e[3]))?e:G):G},yf:function(d){var e;e=this.type(d);return"hex"===e?this.cb(d):"rgb"===e?this.ib(d):"hsl"===e?this.eb(d):G},type:function(d){d=d.toString();return 0<=
d.indexOf("#")||3===d.length||6===d.length?"hex":d.indexOf("%")?"hsl":"rgb"},Qc:function(d){var e,d=this.cb(d);if(!d)return G;e=d.match(/(.{2})(.{2})(.{2})/).slice(1);var h,i,c;c=[];h=0;for(i=e.length;h<i;h++)d=e[h],c.push(parseInt(d,16));return c.push(1)},ne:function(d){if(0<=d.indexOf("#")||6>d.length)d=this.cb(d);return!d?G:this.jd(this.Qc(d))},hd:function(d){var e,h;"string"===typeof d&&(d=this.ib(d));if(d)return h=function(){var h,c,m,q;m=d.slice(0,3);q=[];h=0;for(c=m.length;h<c;h++)e=m[h],q.push(parseFloat(e).toString(16));
return q}(),h=function(){var d,c,m;if(1===e.length)return"0"+e;m=[];d=0;for(c=h.length;d<c;d++)e=h[d],m.push(e);return m}().join(""),"#"+h.toUpperCase()},jd:function(d){var e,h,i,c,m,q,b,v;"string"===typeof d&&(d=this.ib(d));if(!d)return G;v=parseFloat(d[0])/255;c=parseFloat(d[1])/255;h=parseFloat(d[2])/255;q=Math.max(v,c,h);b=Math.min(v,c,h);i=q-b;e=q+b;m=0.5*e;return[Math.round(b===q?0:v===q?(60*(c-h)/i+360)%360:c===q?60*(h-v)/i+120:60*(v-c)/i+240),Math.round(100*(0===m?0:1===m?1:0.5>=m?i/e:i/(2-
e)))+"%",Math.round(100*m)+"%",d[3]||1]},Uc:function(d){var e,h,i;"string"===typeof d&&(d=this.eb(d));if(!d)return G;e=parseInt(d[0])/360;i=parseInt(d[1])/100;h=parseInt(d[2])/100;i=0.5>=h?h*(1+i):h+i-h*i;h=2*h-i;return[Math.round(255*this.$a(h,i,e+1/3)),Math.round(255*this.$a(h,i,e)),Math.round(255*this.$a(h,i,e-1/3)),d[3]||1]},pe:function(d){"string"===typeof d&&(d=this.eb(d));return!d?G:this.hd(this.Uc(d))},$a:function(d,e,h){0>h&&(h+=1);1<h&&(h-=1);return 1>6*h?d+6*(e-d)*h:1>2*h?e:2>3*h?d+6*(e-
d)*(2/3-h):d}};
